
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class AplicantsTable extends javax.swing.JFrame {

    /**
     * Creates new form AplicantsTable
     */
    public AplicantsTable() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        AddBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RefreshBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSplitPane3 = new javax.swing.JSplitPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        employees_Email_Field = new javax.swing.JTextField();
        employees_Id_Field = new javax.swing.JTextField();
        employees_Contract_Field = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        employees_Salary_Field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        UpdteBtn2 = new javax.swing.JButton();
        RefreshBtn2 = new javax.swing.JButton();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        employees_Search_Field = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 33, 35));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APPLICANTS");

        jLayeredPane1.setBackground(new java.awt.Color(0, 82, 82));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Aplying_For :");

        DeleteBtn.setBackground(new java.awt.Color(30, 118, 122));
        DeleteBtn.setForeground(new java.awt.Color(245, 245, 245));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age :");

        jTextField1.setEditable(false);
        jTextField1.setText("       Auto generated");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FT_WORKER", "IT_PROG", "MANAGER", "ACOUNTANT" }));

        jButton3.setBackground(new java.awt.Color(30, 118, 122));
        jButton3.setForeground(new java.awt.Color(245, 245, 245));
        jButton3.setText("HIRE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(18, 18, 50, 1));

        AddBtn.setBackground(new java.awt.Color(30, 118, 122));
        AddBtn.setForeground(new java.awt.Color(245, 245, 245));
        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        ResetBtn.setBackground(new java.awt.Color(30, 118, 122));
        ResetBtn.setForeground(new java.awt.Color(245, 245, 245));
        ResetBtn.setText("RESET");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firstname :");

        RefreshBtn.setBackground(new java.awt.Color(30, 118, 122));
        RefreshBtn.setForeground(new java.awt.Color(245, 245, 245));
        RefreshBtn.setText("REFRESH");
        RefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(30, 118, 122));
        UpdateBtn.setForeground(new java.awt.Color(245, 245, 245));
        UpdateBtn.setText("UPDATE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EducationalAtainment :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lastname :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Adress :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secondary", "Master" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone_No. :");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID :");

        jLayeredPane1.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DeleteBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSpinner1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(AddBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(ResetBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(RefreshBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(UpdateBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLayeredPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jDesktopPane2);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Aplying_For", "Age", "EducationalAtainment", "Phone_No.", "Adress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(4);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jTabbedPane1.addTab("Applicants", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firstname", "Lastname", "Department_ID", "Salary", "Years _Contract", "Hired_date", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(4);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
        }

        jSplitPane2.setRightComponent(jScrollPane2);

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setMinimumSize(new java.awt.Dimension(165, 200));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane3.setTopComponent(jDesktopPane3);

        jDesktopPane5.setMinimumSize(new java.awt.Dimension(200, 160));

        jLayeredPane2.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane2.setMinimumSize(new java.awt.Dimension(170, 170));

        employees_Id_Field.setEditable(false);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email :");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID :");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Years_Contract :");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Salary :");

        UpdteBtn2.setBackground(new java.awt.Color(30, 118, 122));
        UpdteBtn2.setForeground(new java.awt.Color(245, 245, 245));
        UpdteBtn2.setText("UPDATE");
        UpdteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdteBtn2ActionPerformed(evt);
            }
        });

        RefreshBtn2.setBackground(new java.awt.Color(30, 118, 122));
        RefreshBtn2.setForeground(new java.awt.Color(245, 245, 245));
        RefreshBtn2.setText("REFRESH");
        RefreshBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtn2ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(employees_Email_Field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(employees_Id_Field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(employees_Contract_Field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(employees_Salary_Field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(UpdteBtn2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(RefreshBtn2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(RefreshBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(UpdteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(30, 30, 30)
                        .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(employees_Salary_Field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(employees_Email_Field, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employees_Id_Field)
                            .addComponent(employees_Contract_Field))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employees_Id_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employees_Salary_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employees_Contract_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employees_Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdteBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RefreshBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jDesktopPane5.setLayer(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setTopComponent(jDesktopPane5);

        jDesktopPane6.setName(""); // NOI18N

        jLayeredPane3.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        employees_Search_Field.setText("  SEARCH");

        SearchBtn.setBackground(new java.awt.Color(30, 118, 122));
        SearchBtn.setForeground(new java.awt.Color(245, 245, 245));
        SearchBtn.setText("SEARCH");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(employees_Search_Field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(SearchBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employees_Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(employees_Search_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jDesktopPane6.setLayer(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3)
                .addContainerGap())
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane3.setRightComponent(jDesktopPane6);

        jSplitPane2.setLeftComponent(jSplitPane3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1116, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jTabbedPane1.addTab("Employees", jPanel3);

        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private LocalDate currentTime ;
    private boolean error = false;
    private int answer;
    private static Connection con ;
    private static Statement st ;
    private static String sql ;
    private static ResultSet rs ;
    private static DefaultTableModel tbModel ;
    
    public static void updateDB(){
        
      //String URL = "jdbc:mysql//localhost:3306/employees";
      try { 

        Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
        st = con.createStatement();
        sql = "select * from applicants";
        rs = st.executeQuery(sql);
        tbModel = (DefaultTableModel)jTable1.getModel();
        tbModel.setRowCount(0);
        while(rs.next()){
          String ID = String.valueOf(rs.getInt("ID"));
          String Firstname = rs.getString("Firstname");
          String Lastname = rs.getString("Lastname");
          String Age = String.valueOf(rs.getInt("Age"));
          String EducationAtainment = rs.getString("EducationAtainment");
          String Phone_No = rs.getString("Phone_No");
          String Adress = rs.getString("Adress");
          String Applying_For = rs.getString("Applying_For");

          String tbData[] = {ID,Firstname,Lastname,Applying_For,Age,EducationAtainment,Phone_No,Adress};

          tbModel.addRow(tbData);
        }
        con.close();
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    private void connect(){
        
    }
    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
      answer = JOptionPane.showConfirmDialog(null, "Do you want add this Data?",null,JOptionPane.YES_NO_OPTION);

      if(answer == 0){
          try { 
              Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
              con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
              st = con.createStatement();
              sql = "insert into applicants (Firstname,Lastname,Age,EducationAtainment,Phone_No,Adress,Applying_For)values("
                      //+String.valueOf(jTextField1.getText())+","
                      +"\""+jTextField2.getText()+"\""+","
                      +"\""+jTextField3.getText()+"\""+","
                      +String.valueOf(jSpinner1.getValue())+","
                      +"\""+jComboBox2.getSelectedItem()+"\""+","
                      +"\""+jTextField4.getText()+"\""+","
                      +"\""+jTextField5.getText()+"\""+","
                      +"\""+jComboBox1.getSelectedItem()+"\""+")";
              System.out.println(sql);
              st.execute(sql);
              updateDB();

          } catch (ClassNotFoundException ex) {
              error = true;
              JOptionPane.showMessageDialog(null, "Something went wrong");
              Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              error = true;
              JOptionPane.showMessageDialog(null, "error invalid input");
              Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
          }
          if(!error){
              JOptionPane.showMessageDialog(null, "Data successfully added");
          }

       }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        answer = JOptionPane.showConfirmDialog(null, "Do you want Hire "+jTextField2.getText()+" "+jTextField3.getText()+"?",null,JOptionPane.YES_NO_OPTION);
        currentTime = LocalDate.now();
        if(answer == 0){
          try { 
            Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
            st = con.createStatement();
            sql = "insert into employees (Firstname,Lastname,Department_Id,Hired_Date,Age,EducationAtainment,Phone_No,Adress)values("
                    +"\""+jTextField2.getText()+"\""+","
                    +"\""+jTextField3.getText()+"\""+","
                    +"\""+jComboBox1.getSelectedItem()+"\""+","
                    +"\""+currentTime+"\""+","
                    +String.valueOf(jSpinner1.getValue())+","
                    +"\""+jComboBox2.getSelectedItem()+"\""+","
                    +"\""+jTextField4.getText()+"\""+","
                    +"\""+jTextField5.getText()+"\""+");";
            System.out.println(sql);
            st.execute(sql);
            DeleteData();

          } catch (ClassNotFoundException ex) {
            error = true;
            JOptionPane.showMessageDialog(null, "Something went wrong");
            Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
            error = true;
            JOptionPane.showMessageDialog(null, "error invalid input");
            Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
          }
          if(!error){
            JOptionPane.showMessageDialog(null, "Go to eployees tab to update this employee info");
          }
            
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtnActionPerformed
      updateDB(); System.out.println(currentTime);
    }//GEN-LAST:event_RefreshBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
      jTextField1.setText("   Auto generated");
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField4.setText("");
      jTextField5.setText("");
      jComboBox1.setSelectedIndex(0);
      jComboBox2.setSelectedIndex(0);
      jSpinner1.setValue(18);
    }//GEN-LAST:event_ResetBtnActionPerformed
    int selectedrow;
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
      answer = JOptionPane.showConfirmDialog(null, "Do you want to update this data?",null,JOptionPane.YES_NO_OPTION);
      if(answer == 0){
        try { 
          tbModel = (DefaultTableModel)jTable1.getModel();
          Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
          st = con.createStatement();
          sql = "update applicants set"
                  +" ID ="+String.valueOf(jTextField1.getText())+","
                  +"Firstname = "+"\""+jTextField2.getText()+"\""+","
                  + "Lastname = "+"\""+jTextField3.getText()+"\""+","
                  +"Age = "+String.valueOf(jSpinner1.getValue())+","
                  +"EducationAtainment ="+"\""+jComboBox2.getSelectedItem()+"\""+","
                  +"Phone_No ="+"\""+jTextField4.getText()+"\""+","
                  +"Adress ="+"\""+jTextField5.getText()+"\""+","
                  +"Applying_For ="+"\""+jComboBox1.getSelectedItem()+"\""
                  +"where ID = "+tbModel.getValueAt(selectedrow, 0).toString()+";";

          System.out.println(sql);
          st.execute(sql);
          updateDB();

        } catch (ClassNotFoundException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "Something went wrong");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "error invalid input");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!error){
          JOptionPane.showMessageDialog(null, "the selected Data successfully Updated");
        }

      }
    }//GEN-LAST:event_UpdateBtnActionPerformed
    private void DeleteData(){
      try { 
        tbModel = (DefaultTableModel)jTable1.getModel();
        selectedrow = jTable1.getSelectedRow();
        Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
        st = con.createStatement();
        sql = "DELETE FROM applicants WHERE ID ="+tbModel.getValueAt(selectedrow, 0).toString();

        System.out.println(sql);
        st.execute(sql);
        updateDB();

      } catch (ClassNotFoundException ex) {
        error = true;
        JOptionPane.showMessageDialog(null, "something went wrong");
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
        error = true;
        JOptionPane.showMessageDialog(null, "error invalid delete");
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      }
      if(!error){
        JOptionPane.showMessageDialog(null, "The selected Data successfully Deleted");
      }
    }
    
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        
      answer = JOptionPane.showConfirmDialog(null, "Do you want to Delete this data?",null,JOptionPane.YES_NO_OPTION);
      if(answer == 0)
        DeleteData();
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      tbModel = (DefaultTableModel)jTable1.getModel();
      selectedrow = jTable1.getSelectedRow();

      jTextField1.setText(tbModel.getValueAt(selectedrow, 0).toString());
      jTextField2.setText(tbModel.getValueAt(selectedrow, 1).toString());
      jTextField3.setText(tbModel.getValueAt(selectedrow, 2).toString());
      jTextField4.setText(tbModel.getValueAt(selectedrow, 6).toString());
      jTextField5.setText(tbModel.getValueAt(selectedrow, 7).toString());
      jComboBox1.setSelectedItem(tbModel.getValueAt(selectedrow, 3).toString());
      jComboBox2.setSelectedItem(tbModel.getValueAt(selectedrow, 5).toString());
      jSpinner1.setValue(Integer.valueOf(tbModel.getValueAt(selectedrow, 4).toString()));
    }//GEN-LAST:event_jTable1MouseClicked
    public void updateDB2(){
      //String URL = "jdbc:mysql//localhost:3306/employees";
      try { 

        Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
        st = con.createStatement();
        sql = "select * from employees";
        rs = st.executeQuery(sql);
        tbModel = (DefaultTableModel)jTable2.getModel();
        tbModel.setRowCount(0);
        while(rs.next()){
          String ID = String.valueOf(rs.getInt("ID"));
          String Firstname = rs.getString("Firstname");
          String Lastname = rs.getString("Lastname");
          String Department_Id = rs.getString("Department_Id");
          String Salary = String.valueOf(rs.getInt("Salary"));
          String Years_Contract = String.valueOf(rs.getInt("Years_Contract"));
          String Hired_Date = rs.getString("Hired_Date");
          String Email = rs.getString("Email");


          String tbData[] = {ID,Firstname,Lastname,Department_Id,Salary,Years_Contract,Hired_Date,Email};

          tbModel.addRow(tbData);
        }
        con.close();
      } catch (SQLException ex) {
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
        Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      } 
    }
    private void RefreshBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtn2ActionPerformed
       updateDB2();
    }//GEN-LAST:event_RefreshBtn2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      LoginForm lf = new LoginForm();
      answer = JOptionPane.showConfirmDialog(null, "Do you want to exit?",null,JOptionPane.YES_NO_OPTION);
      if(answer == 0){
        this.dispose();
        lf.setVisible(true);
      }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
      tbModel = (DefaultTableModel)jTable2.getModel();
      selectedrow = jTable2.getSelectedRow();

      employees_Id_Field.setText(tbModel.getValueAt(selectedrow, 0).toString());
      employees_Salary_Field.setText(tbModel.getValueAt(selectedrow, 4).toString());
      employees_Contract_Field.setText(tbModel.getValueAt(selectedrow, 5).toString());
      employees_Email_Field.setText((String) tbModel.getValueAt(selectedrow, 7));
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void UpdteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdteBtn2ActionPerformed
      answer = JOptionPane.showConfirmDialog(null, "Do you want to update this data?",null,JOptionPane.YES_NO_OPTION);
      error = false;
      if(answer == 0){
        try { 
          tbModel = (DefaultTableModel)jTable2.getModel();
          Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
          con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
          st = con.createStatement();
          sql = "update employees set "
                  +"Salary = "+String.valueOf(employees_Salary_Field.getText())+","
                  +"Years_Contract ="+String.valueOf(employees_Contract_Field.getText())+","
                  +"Email ="+"\""+employees_Email_Field.getText()+"\""+" "
                  +"where ID = "+tbModel.getValueAt(selectedrow, 0).toString()+";";
          System.out.println(sql);
          st.execute(sql);
          updateDB2();

        } catch (ClassNotFoundException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "Something went wrong");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "error invalid input");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!error){
          JOptionPane.showMessageDialog(null, "the selected Data successfully Updated");
        }
      }
    }//GEN-LAST:event_UpdteBtn2ActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        
      try { 
        tbModel = (DefaultTableModel)jTable2.getModel();
        Class.forName("com.mysql.jdbc.Driver");//?useSSL=false"
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employees?user=root&password=John_Chrl@2006;");//URL,"root","John_Chrl@2006;");
        st = con.createStatement();
        sql = "select * from employees where "+employees_Search_Field.getText();
        rs = st.executeQuery(sql);

        tbModel.setRowCount(0);
        while(rs.next()){
          String ID = String.valueOf(rs.getInt("ID"));
          String Firstname = rs.getString("Firstname");
          String Lastname = rs.getString("Lastname");
          String Department_Id = rs.getString("Department_Id");
          String Salary = String.valueOf(rs.getInt("Salary"));
          String Years_Contract = String.valueOf(rs.getInt("Years_Contract"));
          String Hired_Date = rs.getString("Hired_Date");
          String Email = rs.getString("Email");


          String tbData[] = {ID,Firstname,Lastname,Department_Id,Salary,Years_Contract,Hired_Date,Email};
          tbModel.addRow(tbData);
        }
        con.close();

      } catch (ClassNotFoundException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "Something went wrong");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      } catch (SQLException ex) {
          error = true;
          JOptionPane.showMessageDialog(null, "error invalid input");
          Logger.getLogger(AplicantsTable.class.getName()).log(Level.SEVERE, null, ex);
      }
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              if ("Nimbus".equals(info.getName())) {
                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
      } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(AplicantsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(AplicantsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(AplicantsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(AplicantsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
      updateDB();

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {

          AplicantsTable app = new AplicantsTable();
          app.updateDB();
          app.setVisible(true);
        }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton RefreshBtn;
    private javax.swing.JButton RefreshBtn2;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdteBtn2;
    private javax.swing.JTextField employees_Contract_Field;
    private javax.swing.JTextField employees_Email_Field;
    private javax.swing.JTextField employees_Id_Field;
    private javax.swing.JTextField employees_Salary_Field;
    private javax.swing.JTextField employees_Search_Field;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
