
//import java.io.FileInputStream;
//import java.io.IOException;
//import java.io.ObjectInputStream;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        currentpassTxt = new javax.swing.JTextField();
        newpassTxt = new javax.swing.JTextField();
        confirmpassTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        confrmNewPassword = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "changePassword", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLayeredPane1.add(currentpassTxt);
        currentpassTxt.setBounds(210, 50, 221, 22);
        jLayeredPane1.add(newpassTxt);
        newpassTxt.setBounds(210, 90, 221, 22);

        confirmpassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassTxtActionPerformed(evt);
            }
        });
        jLayeredPane1.add(confirmpassTxt);
        confirmpassTxt.setBounds(210, 130, 221, 22);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current pasword :");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(57, 53, 140, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New pasword :");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(57, 93, 100, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm password :");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(57, 133, 120, 16);

        confrmNewPassword.setBackground(new java.awt.Color(30, 118, 122));
        confrmNewPassword.setForeground(new java.awt.Color(204, 204, 204));
        confrmNewPassword.setText("CONFIRM");
        confrmNewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confrmNewPasswordMouseClicked(evt);
            }
        });
        jLayeredPane1.add(confrmNewPassword);
        confrmNewPassword.setBounds(355, 200, 90, 23);

        jButton2.setBackground(new java.awt.Color(30, 118, 122));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.setText("CANCEL");
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(50, 200, 90, 23);

        jDesktopPane1.add(jLayeredPane1);
        jLayeredPane1.setBounds(20, 20, 510, 280);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 540, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String currentpass ;
    private String newpass;
    private String confirmpass ;
    
    private void confirmpassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassTxtActionPerformed

    private void confrmNewPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confrmNewPasswordMouseClicked
        Acount acount = new Acount();
        Admin admin = new Admin();
        acount.loadSavedAcountInfo();
        
        System.out.println( admin.getPassword());
        currentpass = currentpassTxt.getText();
        newpass = newpassTxt.getText();
        confirmpass = confirmpassTxt.getText();
        
        if(currentpass.equals(admin.getPassword())){
           if(newpass.equals(confirmpass)){
               
               acount.changePassword(newpass);
               LoginForm lf =new LoginForm();
               this.dispose();
               lf.setVisible(true);
               JOptionPane.showMessageDialog(this, "Password changed");
               
           }else{
               JOptionPane.showMessageDialog(this, "confirm your new password");
           }
        }else{
            JOptionPane.showMessageDialog(this, "Current passsword dont match");
        }
        
    }//GEN-LAST:event_confrmNewPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirmpassTxt;
    private javax.swing.JButton confrmNewPassword;
    private javax.swing.JTextField currentpassTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField newpassTxt;
    // End of variables declaration//GEN-END:variables
}
